version: '3'
services:
   h-p-portfolio-nextjs:
    image: h-p-portfolio-nextjs:v1.0
    restart: unless-stopped
    build: .
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      -  h-p-portfolio_network

networks:
   h-p-portfolio_network:
    external: true
